version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    logging:
      options:
        max-size: 1g
    ports:
      - "27017:27017"
    volumes:
      -  ${mongodata}:/data/db
